### ISSUE TITLE
Exception: (550, 'Unknown')

### ISSUE THREAD

**Issue by alexey74** [drewisme/authorizesauce#48]
Several hours ago software using this library started throwing exceptions in `createCustomerProfile`:
```
  Traceback (most recent call last):
  File "authsauce_test.py", line 13, in <module>
    saved_card = card.save()
  File "/home/alexey/git/authorizesauce/authorize/client.py", line 147, in save
    .create_saved_profile(unique_id, [payment], email=self.email)
  File "/home/alexey/git/authorizesauce/authorize/apis/customer.py", line 80, in create_saved_profile
    response = self._make_call('CreateCustomerProfile', profile, 'none')
  File "/home/alexey/git/authorizesauce/authorize/apis/customer.py", line 51, in _make_call
    response = method(self.client_auth, *args)
  File "/home/alexey/.virtualenvs/authorize/lib/python3.6/site-packages/suds/client.py", line 521, in __call__
    return client.invoke(args, kwargs)
  File "/home/alexey/.virtualenvs/authorize/lib/python3.6/site-packages/suds/client.py", line 581, in invoke
    result = self.send(soapenv)
  File "/home/alexey/.virtualenvs/authorize/lib/python3.6/site-packages/suds/client.py", line 619, in send
    description=tostr(e), original_soapenv=original_soapenv)
  File "/home/alexey/.virtualenvs/authorize/lib/python3.6/site-packages/suds/client.py", line 677, in process_reply
    raise Exception((status, description))
Exception: (550, 'Unknown')
```
The API tester here https://developer.authorize.net/api/reference/index.html#customer-profiles-create-customer-profile works fine.

Any insights?

**Comment by alexey74** [comment]
Steps to reproduce:

```
>>> from authorize import AuthorizeClient, CreditCard
>>> client = AuthorizeClient(API_LOGIN, API_SECRET)
>>> cc = CreditCard('4111111111111111', '2018', '11', '911', 'Joe', 'Blow')
>>> card = client.card(cc)
>>> card.capture(100)
<AuthorizeTransaction 60102022389>
>>> saved_card = card.save()
No handlers could be found for logger "suds.client"
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/alexey/.virtualenvs/usgm/local/lib/python2.7/site-packages/authorize/client.py", line 147, in save
    .create_saved_profile(unique_id, [payment], email=self.email)
  File "/home/alexey/.virtualenvs/usgm/local/lib/python2.7/site-packages/authorize/apis/customer.py", line 80, in create_saved_profile
    response = self._make_call('CreateCustomerProfile', profile, 'none')
  File "/home/alexey/.virtualenvs/usgm/local/lib/python2.7/site-packages/authorize/apis/customer.py", line 51, in _make_call
    response = method(self.client_auth, *args)
  File "/home/alexey/.virtualenvs/usgm/local/lib/python2.7/site-packages/suds/client.py", line 542, in __call__
    return client.invoke(args, kwargs)
  File "/home/alexey/.virtualenvs/usgm/local/lib/python2.7/site-packages/suds/client.py", line 602, in invoke
    result = self.send(soapenv)
  File "/home/alexey/.virtualenvs/usgm/local/lib/python2.7/site-packages/suds/client.py", line 649, in send
    result = self.failed(binding, e)
  File "/home/alexey/.virtualenvs/usgm/local/lib/python2.7/site-packages/suds/client.py", line 708, in failed
    raise Exception((status, reason))
Exception: (550, u'Unknown')
```

**Comment by JoshStegmaier** [comment]
That's actually my post on the forums. We've contacting authorize.net through live chat (where they were mostly useless) and over the phone. On the phone, they said CIM had an update yesterday, and that they had at least one other report of someone getting 550 errors.

We've also done some testing, and the JSON/XML API is working for CIM, so it seems to be specific to the SOAP API authorizesauce is using.

**Comment by cpburnz** [comment]
We've been experiencing this same issue since about 7 PM EDT.

**Comment by mohlman3** [comment]
+1

**Comment by mohlman3** [comment]
FWIW I just ended up ripping out AuthorizeSauce for the specific endpoint that was causing the problem.  Still not sure what the root cause is, but I was able to craft a SOAP request manually that succeeded - my wild guess is that Authorize.NET isn't handling namespacing properly.

Here is the code utilizing the official Python SDK I used to replaced the `create_saved_profile` call that was failing, hopefully this will save someone a bit of time if you end up having to replace as well.  (I know OP was making a different call but you can hopefully adapt as needed.)  Authorize has said they are fixing this, but we couldn't wait any longer.

If using pip, add to requirements.txt:

```
authorizenet==1.0.15
```

Code:
```
from authorizenet import apicontractsv1
from authorizenet.apicontrollers import *

merchantAuth = apicontractsv1.merchantAuthenticationType()
merchantAuth.name = settings.AUTHORIZE_NET_API_ID
merchantAuth.transactionKey = settings.AUTHORIZE_NET_API_KEY

createCustomerProfile = apicontractsv1.createCustomerProfileRequest()
createCustomerProfile.merchantAuthentication = merchantAuth
createCustomerProfile.profile = apicontractsv1.customerProfileType()
createCustomerProfile.profile.merchantCustomerId = internal_id
createCustomerProfile.profile.email = email
controller = createCustomerProfileController(createCustomerProfile)
if settings.AUTHORIZE_NET_PRODUCTION:
    controller.setenvironment(constants.PRODUCTION)
controller.execute()
customer_profile_response = controller.getresponse()

customer_profile_id = None
if customer_profile_response.messages.resultCode == "Ok":
    customer_profile_id = customer_profile_response.customerProfileId
```

**Comment by cpburnz** [comment]
@mohlman3 If you create a customer profile using the official SDK (via the XML API), can you then access it using Authorize Sauce (via the SOAP API)?

**Comment by mohlman3** [comment]
@cpburnz Yes that seemed to work fine if referencing it by Authorize.NET's numerical id for the object (`customer_profile_id` in the example above)
